### ISSUE TITLE
di bagian path await ffmpeg(`./${media}`) harus di isi apa yak? kalo di biarin gitu jadi error soalnya

### ISSUE THREAD

**Issue by ahmadxgani** [affisjunianto/botwasapv4#12]
gw bingung di bagian index.js line 1099 path nya harus di isi apa, soalnya error mulu waktu buat stikernya

ketika bikin stiker error seperti ini :

`Started : ffmpeg -i /var/www/latihan/botwasapv4/fmpeg/undefined.jpeg -i undefined.jpeg -y -vcodec libwebp -vf scale='min(320,iw)':min'(320,ih)':force_original_aspect_ratio=decrease,fps=15, pad=320:320:-1:-1:color=white@0.0, split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse -f webp 2194.webp
Error : Error: ffmpeg exited with code 1: /var/www/latihan/botwasapv4/fmpeg/undefined.jpeg: No such file or directory
`

semua sesajen yang ada di install.sh udah gw install semua padhal

**Comment by moo-d** [comment]
Itu cuma nge run command, bukan error
